# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/FPGA/CPU_RIUS/CPU_RIUS.srcs/sources_1/ip/IM/IM.xci
# IP: The module: 'IM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/CPU_RIUS/CPU_RIUS.gen/sources_1/ip/IM/IM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'IM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/FPGA/CPU_RIUS/CPU_RIUS.srcs/sources_1/ip/IM/IM.xci
# IP: The module: 'IM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/CPU_RIUS/CPU_RIUS.gen/sources_1/ip/IM/IM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'IM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
